name: tixcash
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bottom_sheet: ^4.0.0
  webview_flutter: ^4.2.4
#  package_info_plus: ^4.1.0
  overlay_support: ^2.1.0
#  firebase_core: 1.11.0
#  firebase_messaging: 11.2.5
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  dotted_border: 2.0.0+2
  url_launcher: ^6.0.12
  pull_to_refresh: ^2.0.0
  share: 2.0.4
  flutter_slidable: ^3.0.0
  transparent_image: ^2.0.1
  local_auth: ^2.1.7
  qr_flutter: ^4.1.0
  flutter_vector_icons: ^2.0.0
  jiffy: ^6.2.1
  flutter_advanced_drawer: ^1.3.5
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.0
  wave: ^0.2.2
  fluttertoast: ^8.2.2
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  search_page: ^2.3.0
  scoped_model: ^2.0.0
  syncfusion_flutter_pdfviewer: ^22.2.8
  mobile_scanner: 2.1.0
  screenshot: ^2.1.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  permission_handler: ^11.0.1
  qr_code_utils: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter: 
  assets: 
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/icon/
    - assets/text_files/
    - assets/SVG_Icons/
    - assets/

  fonts: 
    - family: KodchasanBold
      fonts: 
        - asset: assets/fonts/KodchasanBold.ttf
  uses-material-design: true